/**
 * Builds src/prompts.generated.ts and prompts/INDEX.md from prompts/**.md.
 *
 *   node scripts/build-prompts.ts          write both files
 *   node scripts/build-prompts.ts --check  exit 1 if either is stale
 *
 * Prompt file format (one file per owner: a tool, the guidelines, wakes):
 *
 *   # <section>            → prompt id "<file stem>.<section>"; the body is
 *   ...body...               every line up to the next "# " heading, with
 *                            leading/trailing blank lines dropped
 *   # rules (list)         → "(list)": the body is "- item" lines → string[]
 *
 * {{name}} is a placeholder, filled with fill(id, vars). An ablatable span is
 * marked <!--seg:segment.id-->…<!--/seg--> (markers are removed from the
 * text; the eval manifest refers to the span by its id).
 *
 * pi loads the extension's TypeScript directly, so the prompts are compiled
 * into a module rather than read at runtime.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const PROMPTS_DIR = join(ROOT, "prompts");
const OUT_TS = join(ROOT, "src", "prompts.generated.ts");
const OUT_INDEX = join(PROMPTS_DIR, "INDEX.md");

export interface PromptEntry {
  id: string;
  file: string;
  value: string | string[];
  vars: string[];
}

export interface SegmentEntry {
  id: string;
  prompt: string;
  /** Exact text when the span has no placeholder. */
  text?: string;
  /** Regex source when it has one (each placeholder matches non-greedily). */
  pattern?: string;
}

const SEG_RE = /<!--seg:([\w.-]+)-->([\s\S]*?)<!--\/seg-->/g;
const VAR_RE = /\{\{(\w+)\}\}/g;

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name);
    if (e.isDirectory()) return walk(p);
    return e.name.endsWith(".md") && e.name !== "INDEX.md" && e.name !== "README.md" ? [p] : [];
  });
}

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export function parsePrompts(dir = PROMPTS_DIR): { prompts: PromptEntry[]; segments: SegmentEntry[] } {
  const prompts: PromptEntry[] = [];
  const segments: SegmentEntry[] = [];
  for (const path of walk(dir).sort()) {
    const file = relative(dir, path).replace(/\\/g, "/");
    const stem = file.replace(/\.md$/, "").replace(/\//g, ".");
    const lines = readFileSync(path, "utf8").split(/\r?\n/);
    const sections: Array<{ name: string; list: boolean; body: string[] }> = [];
    for (const line of lines) {
      const h = /^# (.+?)( \(list\))?$/.exec(line);
      if (h) sections.push({ name: h[1].trim(), list: !!h[2], body: [] });
      else if (sections.length) sections.at(-1)!.body.push(line);
      else if (line.trim() && !line.startsWith("<!--")) throw new Error(`${file}: text before the first "# " heading`);
    }
    for (const s of sections) {
      while (s.body.length && !s.body[0].trim()) s.body.shift();
      while (s.body.length && !s.body.at(-1)!.trim()) s.body.pop();
      const id = `${stem}.${s.name.replace(/[: ]+/g, ".")}`;
      if (prompts.some((p) => p.id === id)) throw new Error(`${file}: duplicate prompt id ${id}`);
      const raw = s.body.join("\n");
      for (const m of raw.matchAll(SEG_RE)) {
        const span = m[2];
        const vars = [...span.matchAll(VAR_RE)];
        segments.push(
          vars.length
            ? { id: m[1], prompt: id, pattern: span.split(VAR_RE).map((part, i) => (i % 2 ? ".*?" : escapeRe(part))).join("") }
            : { id: m[1], prompt: id, text: span },
        );
      }
      const clean = raw.replace(SEG_RE, "$2");
      const value = s.list
        ? clean.split("\n").filter((l) => l.trim()).map((l) => {
            if (!l.startsWith("- ")) throw new Error(`${file} # ${s.name}: list items must start with "- "`);
            return l.slice(2);
          })
        : clean;
      const vars = [...new Set([...(Array.isArray(value) ? value.join("\n") : value).matchAll(VAR_RE)].map((m) => m[1]))];
      prompts.push({ id, file, value, vars });
    }
  }
  const dupSeg = segments.find((s, i) => segments.findIndex((t) => t.id === s.id) !== i);
  if (dupSeg) throw new Error(`duplicate segment id ${dupSeg.id}`);
  return { prompts, segments };
}

export function renderModule({ prompts, segments }: ReturnType<typeof parsePrompts>): string {
  const lit = (v: unknown) => JSON.stringify(v);
  const out = [
    "// Generated by scripts/build-prompts.ts from prompts/. Do not edit; run `npm run prompts`.",
    "",
    "export const PROMPTS = {",
    ...prompts.map((p) => `  ${lit(p.id)}: ${lit(p.value)},`),
    "} as const;",
    "",
    "export type PromptId = keyof typeof PROMPTS;",
    "",
    "/** Placeholder names of each template prompt. */",
    "export interface PromptVars {",
    ...prompts.filter((p) => p.vars.length).map((p) => `  ${lit(p.id)}: ${p.vars.map(lit).join(" | ")};`),
    "}",
    "",
    "/** Fill a template prompt; every placeholder must be given. */",
    "export function fill<K extends keyof PromptVars>(id: K, vars: Record<PromptVars[K], string | number>): string {",
    "  const template = PROMPTS[id] as string;",
    "  return template.replace(/\\{\\{(\\w+)\\}\\}/g, (_, name: string) => {",
    "    const v = (vars as Record<string, string | number>)[name];",
    "    if (v === undefined) throw new Error(`prompt ${id}: missing {{${name}}}`);",
    "    return String(v);",
    "  });",
    "}",
    "",
    "/** Fill every item of a list prompt (rules) that has placeholders. */",
    "export function fillList<K extends keyof PromptVars>(id: K, vars: Record<PromptVars[K], string | number>): string[] {",
    "  return (PROMPTS[id] as readonly string[]).map((item) =>",
    "    item.replace(/\\{\\{(\\w+)\\}\\}/g, (_, name: string) => {",
    "      const v = (vars as Record<string, string | number>)[name];",
    "      if (v === undefined) throw new Error(`prompt ${id}: missing {{${name}}}`);",
    "      return String(v);",
    "    }),",
    "  );",
    "}",
    "",
    "/** Ablatable spans (eval manifest segment ids). */",
    "export const PROMPT_SEGMENTS: Record<string, { prompt: PromptId; text?: string; pattern?: string }> = {",
    ...segments.map((s) => `  ${lit(s.id)}: ${lit({ prompt: s.prompt, ...(s.text !== undefined ? { text: s.text } : { pattern: s.pattern }) })},`),
    "};",
    "",
  ];
  return out.join("\n");
}

export function renderIndex({ prompts, segments }: ReturnType<typeof parsePrompts>): string {
  const rows = prompts.map((p) => {
    const segs = segments.filter((s) => s.prompt === p.id).map((s) => `\`${s.id}\``).join(", ");
    const kind = Array.isArray(p.value) ? `list (${p.value.length})` : p.vars.length ? `template: ${p.vars.map((v) => `\`${v}\``).join(", ")}` : "text";
    return `| \`${p.id}\` | [${p.file}](${p.file}) | ${kind} | ${segs} |`;
  });
  return [
    "# Prompt index",
    "",
    "Every text a model sees from this extension. Generated by `npm run prompts`; edit the files, not this index.",
    "",
    "| id | file | kind | ablatable segments |",
    "|---|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const parsed = parsePrompts();
  const files: Array<[string, string]> = [
    [OUT_TS, renderModule(parsed)],
    [OUT_INDEX, renderIndex(parsed)],
  ];
  if (process.argv.includes("--check")) {
    const stale = files.filter(([p, c]) => {
      try {
        return readFileSync(p, "utf8") !== c;
      } catch {
        return true;
      }
    });
    if (stale.length) {
      console.error(`stale: ${stale.map(([p]) => relative(ROOT, p)).join(", ")} (run npm run prompts)`);
      process.exit(1);
    }
  } else {
    for (const [p, c] of files) writeFileSync(p, c);
    console.log(`${parsed.prompts.length} prompts, ${parsed.segments.length} segments → ${relative(ROOT, OUT_TS)}, ${relative(dirname(OUT_INDEX), OUT_INDEX)}`);
  }
}
